class Blitz
module Curl # :nodoc:
# Use this to run a sprint against your app. The return values include the response
# time, the region from which the sprint was run along with the full request
# and response headers and the response body.
class Sprint
    # Represents the request object generated by the sprint. Contains all
    # of the headers and POST/PUT data, if any.
    class Request
        # The entire request line (GET / HTTP/1.1, for example)
        attr_reader :line
        
        # The method used in the request
        attr_reader :method
        
        # The URL, including path, query arguments and hash fragments
        attr_reader :url
        
        # All of the request headers (as a Hash of name/value pairs)
        attr_reader :headers
        
        # POST/PUT content, if any
        attr_reader :content
        
        def initialize json # :nodoc:
            @line = json['line']
            @method = json['method']
            @url = json['url']
            @content = json['content'].unpack('m')[0]
            @headers = json['headers']
        end
    end
    
    # Represents the response object generated by the sprint. Contains all
    # of the headers and the response payload, if any.
    class Response
        # The entire response line (HTTP/1.1 200 Okay, for example)
        attr_reader :line
        
        # The response status
        attr_reader :status
        
        # The message in the response line
        attr_reader :message
        
        # All of the response headers (as a Hash of name/value pairs)
        attr_reader :headers
        
        # The response content, if any
        attr_reader :content
        
        def initialize json # :nodoc:
            @line = json['line']
            @status = json['status']
            @message = json['message']
            @content = json['content'].unpack('m')[0]
            @headers = json['headers']
        end        
    end
    
    # Contains the result from a successful sprint
    class Result
        # The region from which this sprint was executed
        attr_reader :region
        
        # The overall response time for the successful hit
        attr_reader :duration
        
        # The time it took for the TCP connection
        attr_reader :connect
        
        # The request object containing the URL, headers and content, if any
        attr_reader :request
        
        # The response object containing the status code, headers and content, if any
        attr_reader :response
        
        def initialize json # :nodoc:
            result = json['result']
            @region = result['region']
            @duration = result['duration']
            @connect = result['connect']
            @request = Request.new result['request']
            @response = Response.new result['response']
        end        
    end
    
    # The primary method to execute a sprint from region. This method supports
    # all of the arguments that the blitz bar supports. For example:
    #
    #  args = { 
    #      :url => 'http://www.mudynamics.com',
    #      :headers => [ 'X-API-Token: foo' ],
    #      :region => 'california'
    #  }
    #
    #  result = Blitz::Curl::Sprint.execute args
    def self.execute args
        self.queue(args).result
    end
    
    def self.queue args # :nodoc:
        args.delete 'pattern'
        args.delete :pattern

        res = Command::API.client.curl_execute args
        raise Error.new(res) if res['error']
        return self.new res['job_id']
    end
    
    attr_reader :job_id # :nodoc:
    
    def initialize job_id # :nodoc:
        @job_id = job_id
    end
    
    def result # :nodoc:
        while true
            sleep 2.0

            job = Command::API.client.job_status job_id
            if job['error']
                raise Error
            end

            result = job['result']
            next if job['status'] == 'queued'
            next if job['status'] == 'running' and not result

            raise Error if not result

            error = result['error']
            if error
                if error == 'dns'
                    raise Error::DNS.new(result)
                elsif error == 'connect'
                    raise Error::Connect.new(result)
                elsif error == 'timeout'
                    raise Error::Timeout.new(result)
                elsif error == 'parse'
                    raise Error::Parse.new(result)
                elsif result['assert'] == 0
                    raise Error::Status.new(result)
                else
                    raise Error
                end
            end
            
            return Result.new(job)
        end
    end
    
    def abort # :nodoc:
        Command::API.client.abort_job job_id rescue nil
    end    
end
end # Curl
end # Blitz
